export const COUNTRIES = [
  { id: 7, name: "Afghanistan" },
  { id: 8, name: "Albania" },
  { id: 9, name: "Algeria" },
  { id: 10, name: "Andorra" },
  { id: 11, name: "Angola" },
  { id: 12, name: "Antigua and Barbuda" },
  { id: 13, name: "Argentina" },
  { id: 14, name: "Armenia" },
  { id: 15, name: "Australia" },
  { id: 16, name: "Austria" },
  { id: 17, name: "Azerbaijan" },
  { id: 18, name: "The Bahamas" },
  { id: 19, name: "Bahrain" },
  { id: 20, name: "Bangladesh" },
  { id: 21, name: "Barbados" },
  { id: 22, name: "Belarus" },
  { id: 23, name: "Belgium" },
  { id: 24, name: "Belize" },
  { id: 25, name: "Benin" },
  { id: 26, name: "Bhutan" },
  { id: 27, name: "Bolivia" },
  { id: 28, name: "Bosnia and Herzegovina" },
  { id: 29, name: "Botswana" },
  { id: 30, name: "Brazil" },
  { id: 31, name: "Brunei" },
  { id: 32, name: "Bulgaria" },
  { id: 33, name: "Burkina Faso" },
  { id: 34, name: "Burundi" },
  { id: 35, name: "Cambodia" },
  { id: 36, name: "Cameroon" },
  { id: 37, name: "Canada" },
  { id: 38, name: "Cape Verde" },
  { id: 39, name: "Central African Republic" },
  { id: 40, name: "Chad" },
  { id: 41, name: "Chile" },
  { id: 42, name: "China" },
  { id: 43, name: "Colombia" },
  { id: 44, name: "Comoros" },
  { id: 45, name: "Congo, Republic of the" },
  { id: 46, name: "Congo, Democratic Republic of the" },
  { id: 47, name: "Costa Rica" },
  { id: 48, name: "Cote d'Ivoire" },
  { id: 49, name: "Croatia" },
  { id: 50, name: "Cuba" },
  { id: 51, name: "Cyprus" },
  { id: 52, name: "Czech Republic" },
  { id: 53, name: "Denmark" },
  { id: 54, name: "Djibouti" },
  { id: 55, name: "Dominica" },
  { id: 56, name: "Dominican Republic" },
  { id: 57, name: "East Timor (Timor-Leste)" },
  { id: 58, name: "Ecuador" },
  { id: 59, name: "Egypt" },
  { id: 60, name: "El Salvador" },
  { id: 61, name: "Equatorial Guinea" },
  { id: 62, name: "Eritrea" },
  { id: 63, name: "Estonia" },
  { id: 64, name: "Ethiopia" },
  { id: 65, name: "Fiji" },
  { id: 66, name: "Finland" },
  { id: 67, name: "France" },
  { id: 68, name: "Gabon" },
  { id: 69, name: "The Gambia" },
  { id: 70, name: "Georgia" },
  { id: 71, name: "Germany" },
  { id: 72, name: "Ghana" },
  { id: 73, name: "Greece" },
  { id: 74, name: "Grenada" },
  { id: 75, name: "Guatemala" },
  { id: 76, name: "Guinea" },
  { id: 77, name: "Guinea-Bissau" },
  { id: 78, name: "Guyana" },
  { id: 79, name: "Haiti" },
  { id: 80, name: "Honduras" },
  { id: 81, name: "Hungary" },
  { id: 82, name: "Iceland" },
  { id: 83, name: "India" },
  { id: 84, name: "Indonesia" },
  { id: 85, name: "Iran" },
  { id: 86, name: "Iraq" },
  { id: 87, name: "Ireland" },
  { id: 88, name: "Israel" },
  { id: 89, name: "Italy" },
  { id: 90, name: "Jamaica" },
  { id: 91, name: "Japan" },
  { id: 92, name: "Jordan" },
  { id: 93, name: "Kazakhstan" },
  { id: 94, name: "Kenya" },
  { id: 95, name: "Kiribati" },
  { id: 96, name: "Korea, North" },
  { id: 97, name: "Korea, South" },
  { id: 98, name: "Kosovo" },
  { id: 99, name: "Kuwait" },
  { id: 100, name: "Kyrgyzstan" },
  { id: 101, name: "Laos" },
  { id: 102, name: "Latvia" },
  { id: 103, name: "Lebanon" },
  { id: 104, name: "Lesotho" },
  { id: 105, name: "Liberia" },
  { id: 106, name: "Libya" },
  { id: 107, name: "Liechtenstein" },
  { id: 108, name: "Lithuania" },
  { id: 109, name: "Luxembourg" },
  { id: 110, name: "Macedonia" },
  { id: 111, name: "Madagascar" },
  { id: 112, name: "Malawi" },
  { id: 113, name: "Malaysia" },
  { id: 114, name: "Maldives" },
  { id: 115, name: "Mali" },
  { id: 116, name: "Malta" },
  { id: 117, name: "Marshall Islands" },
  { id: 118, name: "Mauritania" },
  { id: 119, name: "Mauritius" },
  { id: 120, name: "Mexico" },
  { id: 121, name: "Micronesia, Federated States of" },
  { id: 122, name: "Moldova" },
  { id: 123, name: "Monaco" },
  { id: 124, name: "Mongolia" },
  { id: 125, name: "Montenegro" },
  { id: 126, name: "Morocco" },
  { id: 127, name: "Mozambique" },
  { id: 128, name: "Myanmar (Burma)" },
  { id: 129, name: "Namibia" },
  { id: 130, name: "Nauru" },
  { id: 131, name: "Nepal" },
  { id: 132, name: "Netherlands" },
  { id: 133, name: "New Zealand" },
  { id: 134, name: "Nicaragua" },
  { id: 135, name: "Niger" },
  { id: 136, name: "Nigeria" },
  { id: 137, name: "Norway" },
  { id: 138, name: "Oman" },
  { id: 139, name: "Palestine" },
  { id: 140, name: "Pakistan" },
  { id: 141, name: "Palau" },
  { id: 142, name: "Panama" },
  { id: 143, name: "Papua New Guinea" },
  { id: 144, name: "Paraguay" },
  { id: 145, name: "Peru" },
  { id: 146, name: "Philippines" },
  { id: 147, name: "Poland" },
  { id: 148, name: "Portugal" },
  { id: 149, name: "Qatar" },
  { id: 150, name: "Romania" },
  { id: 151, name: "Russia" },
  { id: 152, name: "Rwanda" },
  { id: 153, name: "Saint Kitts and Nevis" },
  { id: 154, name: "Saint Lucia" },
  { id: 155, name: "Saint Vincent and the Grenadines" },
  { id: 156, name: "Samoa" },
  { id: 157, name: "San Marino" },
  { id: 158, name: "Sao Tome and Principe" },
  { id: 159, name: "Saudi Arabia" },
  { id: 160, name: "Senegal" },
  { id: 161, name: "Serbia" },
  { id: 162, name: "Seychelles" },
  { id: 163, name: "Sierra Leone" },
  { id: 164, name: "Singapore" },
  { id: 165, name: "Slovakia" },
  { id: 166, name: "Slovenia" },
  { id: 167, name: "Solomon Islands" },
  { id: 168, name: "Somalia" },
  { id: 169, name: "South Africa" },
  { id: 170, name: "South Sudan" },
  { id: 171, name: "Spain" },
  { id: 172, name: "Sri Lanka" },
  { id: 173, name: "Sudan" },
  { id: 174, name: "Suriname" },
  { id: 175, name: "Swaziland" },
  { id: 176, name: "Sweden" },
  { id: 177, name: "Switzerland" },
  { id: 178, name: "Syria" },
  { id: 179, name: "Taiwan" },
  { id: 180, name: "Tajikistan" },
  { id: 181, name: "Tanzania" },
  { id: 182, name: "Thailand" },
  { id: 183, name: "Togo" },
  { id: 184, name: "Tonga" },
  { id: 185, name: "Trinidad and Tobago" },
  { id: 186, name: "Tunisia" },
  { id: 187, name: "Turkey" },
  { id: 188, name: "Turkmenistan" },
  { id: 189, name: "Tuvalu" },
  { id: 190, name: "Uganda" },
  { id: 191, name: "Ukraine" },
  { id: 192, name: "United Arab Emirates" },
  { id: 193, name: "United Kingdom" },
  { id: 194, name: "United States of America" },
  { id: 195, name: "Uruguay" },
  { id: 196, name: "Uzbekistan" },
  { id: 197, name: "Vanuatu" },
  { id: 198, name: "Vatican City (Holy See)" },
  { id: 199, name: "Venezuela" },
  { id: 200, name: "Vietnam" },
  { id: 201, name: "Yemen" },
  { id: 202, name: "Zambia" },
  { id: 203, name: "Zimbabwe" },
];

export const COUNTRIES_CODE = [
  {id: 1,name :"AF"},
  {id: 2,name :"AX"},
  {id: 3,name :"AL"},
  {id: 4,name :"DZ"},
  {id: 5,name :"AS"},
  {id: 6,name :"AD"},
  {id: 7,name :"AO"},
  {id: 8,name :"AI"},
  {id: 9,name :"AQ"},
  {id: 10,name :"AG"},
  {id: 11,name :"AR"},
  {id: 12,name :"AM"},
  {id: 13,name :"AW"},
  {id: 14,name :"AU"},
  {id: 15,name :"AT"},
  {id: 16,name :"AZ"},
  {id: 17,name :"BH"},
  {id: 18,name :"BS"},
  {id: 19,name :"BD"},
  {id: 20,name :"BB"},
  {id:21,name :"BY"},
  {id: 22,name :"BE"},
  {id: 23,name :"BZ"},
  {id: 24,name :"BJ"},
  {id: 25,name :"BM"},
  {id: 26,name :"BT"},
  {id: 27,name :"BO"},
  {id: 28,name :"BQ"},
  {id: 29,name :"BA"},
  {id: 30,name :"BW"},
  {id: 31,name :"BV"},
  {id: 32,name :"BR"},
  {id: 33,name :"IO"},
  {id: 34,name :"BN"},
  {id: 35,name :"BG"},
  {id: 36,name :"BF"},
  {id: 37,name :"BI"},
  {id: 38,name :"KH"},
  {id: 39,name :"CM"},
  {id: 40,name :"CA"},
  {id: 41,name :"CV"},
  {id: 42,name :"KY"},
  {id: 43,name :"CF"},
  {id: 44,name :"TD"},
  {id: 45,name :"CL"},
  {id: 46,name :"CN"},
  {id: 47,name :"CX"},
  {id: 48,name :"CC"},
  {id: 49,name :"CO"},
  {id: 50,name :"KM"},
  {id: 51,name :"CG"},
  {id: 51,name :"CD"},
  {id: 52,name :"CK"},
  {id: 53,name :"CR"},
  {id: 54,name :"CI"},
  {id: 55,name :"HR"},
  {id: 56,name :"CU"},
  {id: 57,name :"CW"},
  {id: 58,name :"CY"},
  {id: 59,name :"CZ"},
  {id: 60,name :"DK"},
  {id: 61,name :"DJ"},
  {id: 62,name :"DM"},
  {id: 63,name :"DO"},
  {id: 64,name :"EC"},
  {id: 65,name :"EG"},
  {id: 66,name :"SV"},
  {id: 67,name :"GQ"},
  {id: 68,name :"ER"},
  {id: 69,name :"EE"},
  {id: 70,name :"ET"},
  {id: 71,name :"FK"},
  {id: 72,name :"FO"},
  {id: 73,name :"FJ"},
  {id: 74,name :"FI"},
  {id: 75,name :"FR"},
  {id: 76,name :"GF"},
  {id: 77,name :"PF"},
  {id: 78,name :"TF"},
  {id: 79,name :"GA"},
  {id: 80,name :"GM"},
  {id: 81,name :"GE"},
  {id: 82,name :"DE"},
  {id: 83,name :"GH"},
  {id: 84,name :"GI"},
  {id: 85,name :"GR"},
  {id: 86,name :"GL"},
  {id: 87,name :"GD"},
  {id: 88,name :"GP"},
  {id: 89,name :"GU"},
  {id: 90,name :"GT"},
  {id: 91,name :"GG"},
  {id: 92,name :"GN"},
  {id: 93,name :"GW"},
  {id: 94,name :"GY"},
  {id: 95,name :"HT"},
  {id: 96,name :"HM"},
  {id: 97,name :"VA"},
  {id: 98,name :"HN"},
  {id: 99,name :"HK"},
  {id: 100,name :"HU"},
  {id: 101,name :"IS"},
  {id: 102,name :"IN"},
  {id: 103,name :"ID"},
  {id: 104,name :"IR"},
  {id: 105,name :"IQ"},
  {id: 106,name :"IE"},
  {id: 107,name :"IM"},
  {id: 108,name :"IL"},
  {id: 109,name :"IT"},
  {id: 110,name :"JM"},
  {id: 111,name :"JP"},
  {id: 112,name :"JE"},
  {id: 113,name :"JO"},
  {id: 114,name :"KZ"},
  {id: 115,name :"KE"},
  {id: 116,name :"KI"},
  {id: 117,name :"KP"},
  {id: 118,name :"KR"},
  {id: 119,name :"KW"},
  {id: 120,name :"KG"},
  {id: 121,name :"LA"},
  {id: 122,name :"LV"},
  {id: 123,name :"LB"},
  {id: 124,name :"LS"},
  {id: 125,name :"LR"},
  {id: 126,name :"LY"},
  {id: 127,name :"LI"},
  {id: 128,name :"LT"},
  {id: 129,name :"LU"},
  {id: 130,name :"MO"},
  {id: 131,name :"MK"},
  {id: 132,name :"MG"},
  {id: 133,name :"MW"},
  {id: 134,name :"MY"},
  {id: 135,name :"MV"},
  {id: 136,name :"ML"},
  {id: 13,name :"MT"},
  {id: 137,name :"MH"},
  {id: 138,name :"MQ"},
  {id: 139,name :"MR"},
  {id: 140,name :"MU"},
  {id: 141,name :"YT"},
  {id: 142,name :"MX"},
  {id: 143,name :"FM"},
  {id: 144,name :"MD"},
  {id: 145,name :"MC"},
  {id: 146,name :"MN"},
  {id: 147,name :"ME"},
  {id: 148,name :"MS"},
  {id: 149,name :"MA"},
  {id: 150,name :"MZ"},
  {id: 151,name :"MM"},
  {id: 152,name :"NA"},
  {id: 153,name :"NR"},
  {id: 154,name :"NP"},
  {id: 155,name :"NL"},
  {id: 156,name :"NC"},
  {id: 157,name :"NZ"},
  {id: 158,name :"NI"},
  {id: 159,name :"NE"},
  {id: 160,name :"NG"},
  {id: 161,name :"NU"},
  {id: 162,name :"NF"},
  {id: 163,name :"MP"},
  {id: 164,name :"NO"},
  {id: 165,name :"OM"},
  {id: 166,name :"PK"},
  {id: 167,name :"PW"},
  {id: 168,name :"PS"},
  {id: 169,name :"PA"},
  {id: 170,name :"PG"},
  {id: 171,name :"PY"},
  {id: 172,name :"PE"},
  {id: 173,name :"PH"},
  {id: 174,name :"PN"},
  {id: 175,name :"PL"},
  {id: 176,name :"PT"},
  {id: 177,name :"PR"},
  {id: 178,name :"QA"},
  {id: 179,name :"RE"},
  {id: 180,name :"RO"},
  {id: 181,name :"RU"},
  {id: 182,name :"RW"},
  {id: 183,name :"BL"},
  {id: 184,name :"SH"},
  {id: 185,name :"KN"},
  {id: 186,name :"LC"},
  {id: 187,name :"MF"},
  {id: 188,name :"PM"},
  {id: 189,name :"VC"},
  {id: 190,name :"WS"},
  {id: 191,name :"SM"},
  {id: 192,name :"ST"},
  {id: 193,name :"SA"},
  {id: 194,name :"SN"},
  {id: 195,name :"RS"},
  {id: 196,name :"SC"},
  {id: 197,name :"SL"},
  {id: 198,name :"SG"},
  {id: 199,name :"SX"},
  {id: 200,name :"SK"},
  {id: 201,name :"SI"},
  {id: 202,name :"SB"},
  {id: 203,name :"SO"},
  {id: 204,name :"ZA"},
  {id: 205,name :"GS"},
  {id: 206,name :"SS"},
  {id: 207,name :"ES"},
  {id: 207,name :"LK"},
  {id: 208,name :"SD"},
  {id: 209,name :"SR"},
  {id: 210,name :"SJ"},
  {id: 211,name :"SZ"},
  {id: 212,name :"SE"},
  {id: 213,name :"CH"},
  {id: 214,name :"SY"},
  {id: 215,name :"TW"},
  {id: 216,name :"TJ"},
  {id: 217,name :"TZ"},
  {id: 218,name :"TH"},
  {id: 219,name :"TL"},
  {id: 220,name :"TG"},
  {id: 221,name :"TK"},
  {id: 222,name :"TO"},
  {id: 223,name :"TT"},
  {id: 224,name :"TN"},
  {id: 225,name :"TR"},
  {id: 226,name :"TM"},
  {id: 227,name :"TC"},
  {id: 228,name :"TV"},
  {id: 229,name :"UG"},
  {id: 230,name :"UA"},
  {id: 231,name :"AE"},
  {id: 232,name :"GB"},
  {id: 233,name :"US"},
  {id: 234,name :"UM"},
  {id: 235,name :"UY"},
  {id: 236,name :"UZ"},
  {id: 237,name :"VU"},
  {id: 238,name :"VE"},
  {id: 239,name :"VN"},
  {id: 240,name :"VG"},
  {id: 241,name :"VI"},
  {id: 242,name :"WF"},
  {id: 243,name :"EH"},
  {id: 244,name :"YE"},
  {id: 245,name :"ZM"},
  {id: 246,name :"ZW"},
]

export const COUNTRIES_POPULAR = [
  { id: 15, name: "Australia" },
  { id: 37, name: "Canada" },
  { id: 42, name: "China" },
  { id: 67, name: "France" },
  { id: 71, name: "Germany" },
  { id: 83, name: "India" },
  { id: 85, name: "Iran" },
  { id: 86, name: "Iraq" },
  { id: 89, name: "Italy" },
  { id: 91, name: "Japan" },
  { id: 113, name: "Malaysia" },
  { id: 140, name: "Pakistan" },
  { id: 151, name: "Russia" },
  { id: 159, name: "Saudi Arabia" },
  { id: 169, name: "South Africa" },
  { id: 192, name: "United Arab Emirates" },
  { id: 193, name: "United Kingdom" },
  { id: 194, name: "United States of America" },
];

export const LANGUAGES = [
  { id: 1, name: "Arabic" },
  { id: 2, name: "Balochi" },
  { id: 3, name: "Bangla" },
  { id: 4, name: "Cantonese" },
  { id: 5, name: "Dutch" },
  { id: 6, name: "English" },
  { id: 31, name: "Icelandic" },
  { id: 7, name: "Farsi" },
  { id: 8, name: "French" },
  { id: 9, name: "German" },
  { id: 10, name: "Gujarati" },
  { id: 11, name: "Hindi" },
  { id: 12, name: "Italian" },
  { id: 13, name: "Karanese" },
  { id: 14, name: "Kashmiri" },
  { id: 15, name: "Korean" },
  { id: 16, name: "Kurdish" },
  { id: 17, name: "Malyalam" },
  { id: 18, name: "Mandarin" },
  { id: 19, name: "Marathi" },
  { id: 20, name: "Pashto" },
  { id: 21, name: "Portuguese" },
  { id: 22, name: "Punjabi" },
  { id: 23, name: "Sindhi" },
  { id: 24, name: "Spanish" },
  { id: 25, name: "Tamil" },
  { id: 26, name: "Telugu" },
  { id: 27, name: "Turkish" },
  { id: 28, name: "Urdu" },
  { id: 29, name: "Uzbek" },
  { id: 30, name: "Other" },
];

export const EXPERIENCE = [
  { id: 1, name: "< 1 year" },
  { id: 2, name: "1 year" },
  { id: 3, name: "2 years" },
  { id: 4, name: "3 years" },
  { id: 5, name: "4 years" },
  { id: 6, name: "5 years" },
  { id: 7, name: "6 years" },
  { id: 8, name: "7 years" },
  { id: 9, name: "8 years" },
  { id: 10, name: "9 years" },
  { id: 11, name: "10 years" },
  { id: 11, name: "10+ years" },
];

export const TYPE = [
  { id: 1, name: "company" },
  { id: 1, name: "person" },
];

export const CONTACT_TYPE = [
  { id: 1, name: "business" },
  { id: 1, name: "personal" },
];
